modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All rights reserved"

[[mods]]
modId="rpgmod"
version="1.0.0"
displayName="Mod RPG"
authors="Los Heroes del Norte"
description='''
Mod tipo RPG con sistema de personajes intercambiables y un jefe final.
Desarrollado como proyecto final de la materia de Programación Orientada a Objetos.
'''

[[dependencies.rpgmod]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.rpgmod]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"